"use client";

import { useState } from "react";
import { Activity, Bot, CheckCircle2, FileText, Play, RefreshCcw, Search, Send, Sparkles } from "lucide-react";
import type { Demo } from "@/lib/types";

const steps = ["Context loaded", "Evidence reviewed", "Response generated"];

export function MockApp({ demo }: { demo: Demo }) {
  const [selected, setSelected] = useState(demo.prompts[0]);
  const [status, setStatus] = useState<"idle" | "running" | "done">("idle");
  const run = () => { setStatus("running"); window.setTimeout(() => setStatus("done"), 900); };
  const reset = () => { setStatus("idle"); setSelected(demo.prompts[0]); };
  const isVision = demo.archetype === "vision";
  const isWorkflow = demo.archetype === "workflow";
  const isDocument = demo.archetype === "documents" || demo.archetype === "research";
  return <div className="overflow-hidden rounded-3xl border border-[var(--line)] bg-[#07101e] text-white shadow-2xl shadow-blue-950/30">
    <div className="flex items-center justify-between border-b border-white/10 px-5 py-3"><div className="flex items-center gap-2"><span className="size-2 rounded-full bg-emerald-400"/><span className="text-xs font-bold uppercase tracking-widest text-slate-300">Live simulation</span></div><button onClick={reset} className="flex items-center gap-2 rounded-lg px-3 py-2 text-xs text-slate-300 hover:bg-white/5"><RefreshCcw size={13}/> Reset</button></div>
    <div className="grid min-h-[500px] md:grid-cols-[220px_1fr]">
      <aside className="border-b border-white/10 bg-white/[.025] p-4 md:border-b-0 md:border-r"><p className="px-2 text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">Suggested actions</p><div className="mt-3 space-y-2">{demo.prompts.map((prompt) => <button key={prompt} onClick={() => { setSelected(prompt); setStatus("idle"); }} className={`w-full rounded-xl p-3 text-left text-xs leading-5 transition ${selected === prompt ? "bg-blue-600 text-white" : "text-slate-300 hover:bg-white/5"}`}>{prompt}</button>)}</div><div className="mt-8 rounded-xl border border-white/10 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Data boundary</p><p className="mt-2 text-xs leading-5 text-slate-300">Illustrative local workspace<br/>3 approved sources</p></div></aside>
      <div className="p-5 md:p-7">
        <div className="flex items-start justify-between gap-5"><div><p className="text-xs font-bold text-blue-400">{demo.industry}</p><h3 className="mt-1 text-xl font-bold">{demo.name} Workspace</h3></div><span className="rounded-full bg-emerald-400/10 px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider text-emerald-300">Ready</span></div>
        {isVision ? <VisionSurface done={status === "done"}/> : isWorkflow ? <WorkflowSurface done={status === "done"}/> : isDocument ? <DocumentSurface done={status === "done"}/> : <CopilotSurface done={status === "done"} selected={selected}/>}
        <div className="mt-5 flex flex-col gap-3 rounded-2xl border border-white/10 bg-white/[.03] p-3 sm:flex-row sm:items-center"><div className="flex flex-1 items-center gap-3 px-2"><Sparkles size={17} className="text-blue-400"/><span className="text-sm text-slate-300">{selected}</span></div><button disabled={status === "running"} onClick={run} className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold transition hover:bg-blue-500 disabled:opacity-60">{status === "running" ? <><Activity className="animate-spin" size={16}/> Simulating</> : <>{demo.archetype === "copilot" ? <Send size={16}/> : <Play size={16}/>} Run</>}</button></div>
      </div>
    </div>
  </div>;
}

function CopilotSurface({ done, selected }: { done: boolean; selected: string }) { return <div className="mt-6 space-y-3"><div className="ml-auto max-w-md rounded-2xl rounded-tr-sm bg-blue-600 p-4 text-sm">{selected}</div><div className="max-w-xl rounded-2xl rounded-tl-sm border border-white/10 bg-white/5 p-5"><div className="flex items-center gap-2 text-xs font-bold text-blue-300"><Bot size={16}/> ASSISTANT</div>{done ? <><p className="mt-4 text-sm leading-6 text-slate-200">I reviewed the approved context and prepared a structured response. The highest-priority action is to validate the missing information before advancing the case.</p><div className="mt-4 flex gap-2 text-[10px] text-slate-400"><span className="rounded bg-white/5 px-2 py-1">Policy guide · p.12</span><span className="rounded bg-white/5 px-2 py-1">Case record · 04</span></div></> : <p className="mt-4 text-sm text-slate-500">Choose an action and run the simulation.</p>}</div></div> }
function DocumentSurface({ done }: { done: boolean }) { return <div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/5 p-5 sm:col-span-2"><div className="flex items-center gap-2 text-xs font-bold text-slate-300"><FileText size={15}/> SELECTED DOCUMENT</div><div className="mt-5 space-y-3">{[92,76,84,60].map((width, i) => <div key={i} className={`h-2 rounded bg-white/10 ${done && i === 1 ? "ring-2 ring-blue-400" : ""}`} style={{ width: `${width}%` }}/>)}</div></div><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><p className="text-xs font-bold text-slate-300">EXTRACTED</p>{done ? <div className="mt-4 space-y-3 text-xs">{["6 entities", "2 dates", "1 review flag"].map(x => <div key={x} className="flex items-center gap-2"><CheckCircle2 size={14} className="text-emerald-400"/>{x}</div>)}</div> : <p className="mt-4 text-xs text-slate-500">Awaiting analysis</p>}</div></div> }
function VisionSurface({ done }: { done: boolean }) { return <div className="relative mt-6 h-64 overflow-hidden rounded-2xl border border-white/10 bg-[linear-gradient(135deg,#142234,#08111e)]"><div className="absolute inset-0 grid grid-cols-6 grid-rows-4 opacity-20">{Array.from({length:24}).map((_,i)=><span key={i} className="border border-blue-300/30"/>)}</div><div className="absolute left-[28%] top-[24%] size-24 rounded-xl border-2 border-emerald-400"><span className="absolute -top-6 left-0 rounded bg-emerald-400 px-2 py-1 text-[9px] font-bold text-black">ASSEMBLY · 98%</span></div>{done && <div className="absolute right-[17%] top-[48%] size-16 rounded-lg border-2 border-amber-400"><span className="absolute -top-6 right-0 whitespace-nowrap rounded bg-amber-400 px-2 py-1 text-[9px] font-bold text-black">REVIEW · 72%</span></div>}<div className="absolute bottom-4 left-4 flex items-center gap-2 rounded-lg bg-black/50 px-3 py-2 text-xs"><Search size={14}/> Camera 02 · Inspection lane</div></div> }
function WorkflowSurface({ done }: { done: boolean }) { return <div className="mt-6 grid gap-3 sm:grid-cols-3">{steps.map((step, i) => <div key={step} className={`rounded-2xl border p-5 ${done || i === 0 ? "border-blue-400/40 bg-blue-400/10" : "border-white/10 bg-white/[.03]"}`}><div className="flex items-center justify-between"><span className="grid size-7 place-items-center rounded-full bg-white/10 text-xs">{i+1}</span>{(done || i === 0) && <CheckCircle2 size={15} className="text-emerald-400"/>}</div><p className="mt-8 text-sm font-bold">{step}</p><p className="mt-2 text-[10px] text-slate-500">{done ? "Completed with audit log" : i === 0 ? "Ready to advance" : "Waiting for handoff"}</p></div>)}</div> }
