"use client";

import * as Dialog from "@radix-ui/react-dialog";
import Link from "next/link";
import { ArrowRight, Check, Cpu, ExternalLink, X } from "lucide-react";
import { useApp } from "./app-provider";
import { hardwareProfiles, getPlatformModelExamples, getWorkloadStack } from "@/data/technology";
import type { Demo, Platform } from "@/lib/types";

export function TechnologyStackCard({ demo, platform }: { demo: Demo; platform?: Platform }) {
  const { selection } = useApp();
  const selectedPlatform = platform ?? selection?.platform;
  if (!selectedPlatform) return <div className="panel rounded-3xl p-6"><span className="grid size-11 place-items-center rounded-xl bg-amber-500/10 text-amber-500"><Cpu size={20}/></span><p className="eyebrow mt-8">Technology stack</p><h2 className="mt-2 text-2xl font-black">Choose a platform first</h2><p className="muted mt-3 text-sm leading-6">Select Nano or Fury to see hardware specifications and a qualified workload stack for this experience.</p><Link href="/" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-blue-500">Choose a device <ArrowRight size={15}/></Link></div>;
  const hardware = hardwareProfiles[selectedPlatform];
  const stack = getWorkloadStack(demo.archetype);
  const modelExamples = getPlatformModelExamples(demo.archetype, selectedPlatform);
  return <Dialog.Root><Dialog.Trigger asChild><button className="panel group w-full rounded-3xl p-6 text-left transition hover:border-blue-500"><div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-xl bg-blue-500/10 text-blue-500"><Cpu size={20}/></span><ArrowRight size={18} className="transition group-hover:translate-x-1"/></div><p className="eyebrow mt-8">Technology stack</p><p className="mt-2 text-2xl font-black">{hardware.name}</p><p className="muted mt-3 text-sm leading-6">{hardware.positioning}</p><p className="mt-5 text-xs font-bold text-blue-500">EXPLORE HARDWARE + MODELS</p></button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm"/><Dialog.Content className="panel fixed left-1/2 top-1/2 z-50 max-h-[92vh] w-[min(820px,calc(100%-32px))] -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-3xl p-7 md:p-9"><div className="flex items-start justify-between gap-5"><div><p className="eyebrow">Selected technology stack</p><Dialog.Title className="mt-2 text-3xl font-black">{hardware.name}</Dialog.Title><Dialog.Description className="muted mt-3">{demo.name} · {demo.workload}</Dialog.Description></div><Dialog.Close className="grid size-9 shrink-0 place-items-center rounded-full border border-[var(--line)]"><X size={17}/></Dialog.Close></div>
      <div className="mt-7 grid gap-3 sm:grid-cols-2">{[["Superchip",hardware.superchip],["CPU / unified memory",hardware.cpuMemory],["GPU memory",hardware.gpuMemory],["Memory bandwidth",hardware.memoryBandwidth],["Operating system",hardware.operatingSystem],["Software",hardware.software.join(" · ")]].map(([key,value])=><div key={key} className="rounded-xl border border-[var(--line)] p-4"><p className="muted text-xs">{key}</p><p className="mt-1 text-sm font-bold leading-5">{value}</p></div>)}</div>
      <h3 className="mt-8 text-lg font-black">Why this platform can support the stack</h3><div className="mt-4 space-y-3">{stack.fit[selectedPlatform].map((reason)=><div key={reason} className="flex items-start gap-3 text-sm leading-6"><span className="mt-1 grid size-5 shrink-0 place-items-center rounded-full bg-emerald-500/10 text-emerald-500"><Check size={12}/></span>{reason}</div>)}</div>
      <h3 className="mt-8 text-lg font-black">Qualified model examples</h3><div className="mt-4 space-y-3">{modelExamples.map((model)=><div key={model.name} className="rounded-xl border border-[var(--line)] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-black">{model.name}</p><span className="rounded-full bg-blue-500/10 px-2.5 py-1 text-[10px] font-bold text-blue-500">{model.category}</span></div><p className="muted mt-2 text-sm">{model.role}</p><p className="mt-2 text-xs font-bold">{model.sizing}</p></div>)}</div>
      <section className="mt-8 rounded-2xl bg-blue-500/6 p-5"><h3 className="font-black">Why local?</h3><div className="muted mt-3 grid gap-3 text-sm leading-6 sm:grid-cols-2"><p><b className="text-[var(--text)]">Control:</b> Keep governed data, retrieval indexes, and model workflows in the chosen environment.</p><p><b className="text-[var(--text)]">Predictability:</b> Shift suitable workloads from usage-based services to owned capacity.</p><p><b className="text-[var(--text)]">Customization:</b> Adapt models and workflows around proprietary context and policies.</p><p><b className="text-[var(--text)]">Tradeoff:</b> Local deployment adds operational ownership and is not always less expensive than SaaS.</p></div></section>
      <section className="mt-4 rounded-2xl border border-[var(--line)] p-5"><h3 className="font-black">Workload economics</h3><p className="muted mt-3 text-sm leading-6">{selectedPlatform === "nano" ? "Nano is the lower-complexity entry point for dedicated-user experiments, bounded inference, and proof-of-concept work where departmental serving capacity is unnecessary." : "Fury is economically strongest for sustained departmental utilization, concurrent serving, sensitive data with high data gravity, or large-model workflows that would otherwise create recurring cloud inference, transfer, and access costs."}</p><p className="mt-3 text-xs font-semibold text-amber-600 dark:text-amber-200">Scenario guidance only. Acquisition cost, utilization, operations, energy, integration, and cloud contract terms must be measured before making a TCO claim.</p></section>
      <div className="mt-7 rounded-xl border border-amber-500/20 bg-amber-500/5 p-4 text-xs leading-5 text-amber-700 dark:text-amber-200">Model fit estimates are educational starting points. Weights are only part of memory demand; precision, KV cache, context length, batching, framework overhead, and latency targets must be validated. These examples are not certifications.</div>
      <div className="mt-6 flex flex-wrap items-center justify-between gap-3 text-xs"><a href={hardware.sourceUrl} target="_blank" rel="noreferrer" className="muted inline-flex items-center gap-2 font-bold">Official specification source <ExternalLink size={13}/></a><div className="flex items-center gap-4"><span className="muted">Reviewed {hardware.reviewedAt}</span><Link href="/" className="font-bold text-blue-500">Change device</Link></div></div>
    </Dialog.Content></Dialog.Portal></Dialog.Root>;
}
