"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Image from "next/image";
import { AlertTriangle, ArrowLeft, Check, ChevronDown, CircleHelp, Clipboard, Eye, EyeOff, FileText, History, Minus, PanelRight, Plus, RotateCcw, ScanLine, SlidersHorizontal, X } from "lucide-react";
import type { SimulationProps, SimulationState } from "../contracts";
import { ResetControl } from "../shared/common-controls";
import { SimulationHeader } from "../shared/simulation-header";
import { SimulationShell } from "../shared/simulation-shell";
import { buildReport, initialAudit, reportContext, studies, type AiStatus, type Disposition, type Study } from "./mock-data";
import chestImage from "./chest-synthetic.svg";

type Screen = "worklist" | "loading" | "viewer";
type Sort = "priority" | "time";
const stages = ["Validating synthetic study", "Normalizing image", "Running compact CXR model", "Preparing attention map"];

export function RadiologyAssistantSimulation({ demo }: SimulationProps) {
  const timers = useRef<number[]>([]);
  const [screen, setScreen] = useState<Screen>("worklist");
  const [selectedId, setSelectedId] = useState(studies[0].id);
  const [statuses, setStatuses] = useState<Record<string, AiStatus>>(() => Object.fromEntries(studies.map((s) => [s.id, s.aiStatus])));
  const [analysis, setAnalysis] = useState<"idle" | "processing" | "success" | "error">("idle");
  const [stage, setStage] = useState(0);
  const [overlay, setOverlay] = useState(true);
  const [annotations, setAnnotations] = useState(true);
  const [zoom, setZoom] = useState(100);
  const [brightness, setBrightness] = useState(100);
  const [contrast, setContrast] = useState(100);
  const [disposition, setDisposition] = useState<Disposition>("pending");
  const [report, setReport] = useState("");
  const [audit, setAudit] = useState(initialAudit);
  const [priorityFilter, setPriorityFilter] = useState("All priorities");
  const [aiFilter, setAiFilter] = useState("All AI states");
  const [modality, setModality] = useState("All modalities");
  const [sort, setSort] = useState<Sort>("priority");
  const [activeTab, setActiveTab] = useState<"finding" | "report" | "history">("finding");
  const [copied, setCopied] = useState(false);
  const selected = studies.find((s) => s.id === selectedId) ?? studies[0];
  const currentStatus = statuses[selected.id];

  const clearTimers = () => { timers.current.forEach(window.clearTimeout); timers.current = []; };
  useEffect(() => () => clearTimers(), []);
  const reset = () => {
    clearTimers(); setScreen("worklist"); setSelectedId(studies[0].id); setStatuses(Object.fromEntries(studies.map((s) => [s.id, s.aiStatus]))); setAnalysis("idle"); setStage(0); setOverlay(true); setAnnotations(true); setZoom(100); setBrightness(100); setContrast(100); setDisposition("pending"); setReport(""); setAudit(initialAudit); setPriorityFilter("All priorities"); setAiFilter("All AI states"); setModality("All modalities"); setSort("priority"); setActiveTab("finding"); setCopied(false);
  };
  const openStudy = (study: Study) => {
    clearTimers(); setSelectedId(study.id); setScreen("loading"); setAnalysis("idle"); setDisposition("pending"); setReport(""); setAudit([`${study.time} · Study received from simulated RIS`, `${study.time} · Synthetic images available`]);
    timers.current.push(window.setTimeout(() => setScreen("viewer"), 350));
  };
  const analyze = (ignoreQueuedError = false) => {
    clearTimers(); setAnalysis("processing"); setStage(0); setActiveTab("finding"); setAudit((a) => [...a, "AI analysis started · local scripted pipeline"]);
    if (selected.id === "study-error") return;
    [1, 2, 3].forEach((next) => timers.current.push(window.setTimeout(() => setStage(next), next * 350)));
    timers.current.push(window.setTimeout(() => {
      if (selected.id === "study-urgent" && currentStatus === "error" && !ignoreQueuedError) { setAnalysis("error"); setAudit((a) => [...a, "Processing interrupted · simulated recoverable error"]); return; }
      const next = selected.finding ? "attention" : "clear";
      setStatuses((value) => ({ ...value, [selected.id]: next })); setAnalysis("success");
      setAudit((a) => [...a, selected.finding ? "Suspected finding available for review" : "Analysis complete · no suspected finding"]);
    }, 1500));
  };
  const retry = () => { setStatuses((v) => ({ ...v, [selected.id]: "queued" })); analyze(true); };
  const dispositionFinding = (value: Disposition) => {
    setDisposition(value); setAudit((a) => [...a, `${selected.finding?.name} marked ${value}`]);
    if (report) setReport(buildReport(selected, value));
  };
  const generateReport = () => { setReport(buildReport(selected, disposition)); setActiveTab("report"); setAudit((a) => [...a, "Structured draft generated · radiologist review required"]); };
  const copyReport = async () => { if (!navigator.clipboard || !report) return; await navigator.clipboard.writeText(report); setCopied(true); };
  const state: SimulationState = screen === "worklist" ? "initial" : analysis === "processing" || screen === "loading" ? "processing" : analysis === "error" ? "error" : analysis === "success" && !selected.finding ? "empty" : analysis === "success" ? "success" : "initial";
  const filtered = useMemo(() => studies.filter((s) => (priorityFilter === "All priorities" || s.priority === priorityFilter) && (modality === "All modalities" || s.modality === modality) && (aiFilter === "All AI states" || statusLabel(statuses[s.id]) === aiFilter)).sort((a, b) => sort === "priority" ? priorityRank(statuses[b.id], b.priority) - priorityRank(statuses[a.id], a.priority) : a.time.localeCompare(b.time)), [priorityFilter, modality, aiFilter, sort, statuses]);

  return <SimulationShell header={<SimulationHeader eyebrow="Local diagnostic workflow · simulated" title={`${demo.name} / CXR Review`} state={state} actions={<ResetControl onReset={reset}/>}/>}>
    {screen === "worklist" ? <Worklist studies={filtered} statuses={statuses} filters={{ priorityFilter, aiFilter, modality, sort }} setFilters={{ setPriorityFilter, setAiFilter, setModality, setSort }} onOpen={openStudy} onSimulateError={() => { setStatuses((v) => ({ ...v, "study-urgent": "error" })); openStudy(studies[0]); }}/>
      : screen === "loading" ? <div className="grid min-h-[560px] place-items-center"><div className="text-center"><ScanLine className="mx-auto animate-pulse text-blue-400" size={36}/><p className="mt-4 text-sm font-bold">Loading synthetic study</p><p className="mt-2 text-xs text-slate-500">Preparing diagnostic workspace…</p></div></div>
      : <Viewer study={selected} currentStatus={currentStatus} analysis={analysis} stage={stage} overlay={overlay} annotations={annotations} zoom={zoom} brightness={brightness} contrast={contrast} disposition={disposition} report={report} audit={audit} activeTab={activeTab} copied={copied} onBack={() => setScreen("worklist")} onSelectStudy={openStudy} onAnalyze={() => analyze()} onRetry={retry} onOverlay={() => setOverlay((v) => !v)} onAnnotations={() => setAnnotations((v) => !v)} onZoom={setZoom} onBrightness={setBrightness} onContrast={setContrast} onResetView={() => { setZoom(100); setBrightness(100); setContrast(100); }} onDisposition={dispositionFinding} onGenerate={generateReport} onReport={setReport} onTab={setActiveTab} onCopy={copyReport}/>}
  </SimulationShell>;
}

function Worklist({ studies: visible, statuses, filters, setFilters, onOpen, onSimulateError }: { studies: Study[]; statuses: Record<string, AiStatus>; filters: { priorityFilter: string; aiFilter: string; modality: string; sort: Sort }; setFilters: { setPriorityFilter: (v: string) => void; setAiFilter: (v: string) => void; setModality: (v: string) => void; setSort: (v: Sort) => void }; onOpen: (s: Study) => void; onSimulateError: () => void }) {
  return <div className="min-h-[560px] text-slate-200"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-white/10 pb-4"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">Reading worklist</p><h3 className="mt-1 text-lg font-bold">Chest radiography · 3 unread</h3></div><div className="flex flex-wrap gap-2"><Select label="Priority" value={filters.priorityFilter} values={["All priorities", "STAT", "Routine"]} onChange={setFilters.setPriorityFilter}/><Select label="Modality" value={filters.modality} values={["All modalities", "DX"]} onChange={setFilters.setModality}/><Select label="AI status" value={filters.aiFilter} values={["All AI states", "Pending", "Attention", "No finding"]} onChange={setFilters.setAiFilter}/><button type="button" onClick={() => setFilters.setSort(filters.sort === "priority" ? "time" : "priority")} className="rounded-md border border-white/10 px-3 py-2 text-xs hover:bg-white/5">Sort: {filters.sort}</button></div></div>
    <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[760px] border-collapse text-left text-xs"><thead className="text-[10px] uppercase tracking-wider text-slate-500"><tr>{["Priority", "Patient", "Exam", "Mod", "Accession", "Received", "AI status", "Prior"].map((h) => <th key={h} className="border-b border-white/10 px-3 py-3 font-bold">{h}</th>)}</tr></thead><tbody>{visible.map((study) => <tr key={study.id} tabIndex={0} onClick={() => onOpen(study)} onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); onOpen(study); } }} className="cursor-pointer border-b border-white/[.06] hover:bg-white/[.04] focus:bg-blue-500/10 focus:outline-none"><td className="px-3 py-4"><Priority value={study.priority}/></td><td className="px-3 py-4"><b className="text-white">{study.patient}</b><span className="mt-1 block text-[10px] text-slate-500">{study.ageSex} · fictional</span></td><td className="px-3 py-4">{study.exam}</td><td className="px-3 py-4 font-mono">{study.modality}</td><td className="px-3 py-4 font-mono text-slate-400">{study.accession}</td><td className="px-3 py-4">{study.time}</td><td className="px-3 py-4"><AiBadge status={statuses[study.id]}/></td><td className="px-3 py-4 text-slate-400">{study.comparison}</td></tr>)}</tbody></table>{visible.length === 0 && <p className="py-16 text-center text-sm text-slate-500">No studies match the active filters.</p>}</div>
    <div className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-lg border border-white/10 bg-white/[.025] px-4 py-3 text-[11px] text-slate-400"><span>Fictional patients · synthetic identifiers · deterministic local data</span><button type="button" onClick={onSimulateError} className="rounded px-2 py-1 text-amber-300 hover:bg-amber-400/10">Load recoverable error scenario</button></div></div>;
}

function Viewer(p: { study: Study; currentStatus: AiStatus; analysis: string; stage: number; overlay: boolean; annotations: boolean; zoom: number; brightness: number; contrast: number; disposition: Disposition; report: string; audit: string[]; activeTab: "finding" | "report" | "history"; copied: boolean; onBack: () => void; onSelectStudy: (s: Study) => void; onAnalyze: () => void; onRetry: () => void; onOverlay: () => void; onAnnotations: () => void; onZoom: (v: number) => void; onBrightness: (v: number) => void; onContrast: (v: number) => void; onResetView: () => void; onDisposition: (v: Disposition) => void; onGenerate: () => void; onReport: (v: string) => void; onTab: (v: "finding" | "report" | "history") => void; onCopy: () => void }) {
  const resultReady = p.analysis === "success";
  return <div className="-m-5 min-h-[640px] bg-[#05090f] md:-m-7"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-white/10 bg-[#101720] px-3 py-2"><div className="flex items-center gap-2"><button type="button" onClick={p.onBack} className="rounded p-2 hover:bg-white/5" aria-label="Return to worklist" title="Return to worklist"><ArrowLeft size={16}/></button><div><p className="text-xs font-bold">{p.study.patient} <span className="font-normal text-slate-400">{p.study.ageSex}</span></p><p className="text-[10px] text-slate-500">{p.study.accession} · {p.study.exam} · {p.study.time}</p></div></div><div className="flex items-center gap-2"><Priority value={p.study.priority}/><AiBadge status={p.currentStatus}/><button type="button" onClick={p.onAnalyze} disabled={p.analysis === "processing"} className="rounded bg-blue-600 px-3 py-2 text-xs font-bold hover:bg-blue-500 disabled:opacity-50">{p.analysis === "processing" ? "Analyzing…" : "Start AI analysis"}</button></div></div>
    <div className="grid min-h-[590px] lg:grid-cols-[150px_minmax(420px,1fr)_350px]"><aside className="border-b border-white/10 bg-[#0b1119] p-2 lg:border-b-0 lg:border-r"><p className="px-2 py-2 text-[9px] font-bold uppercase tracking-wider text-slate-500">Study navigator</p>{studies.map((s) => <button type="button" key={s.id} onClick={() => p.onSelectStudy(s)} className={`mb-2 w-full rounded border p-2 text-left ${s.id === p.study.id ? "border-blue-500 bg-blue-500/10" : "border-white/10 hover:bg-white/5"}`}><div className="h-16 rounded bg-[radial-gradient(circle,#66717d,#121820_70%)]"/><p className="mt-2 truncate text-[10px] font-bold">{s.patient}</p><p className="text-[9px] text-slate-500">{s.exam}</p></button>)}</aside>
      <main className="min-w-0 border-b border-white/10 lg:border-b-0 lg:border-r"><ViewerToolbar {...p}/><div className="relative flex h-[430px] items-center justify-center overflow-hidden bg-black"><div className="relative h-full max-h-[430px] aspect-[5/6] transition-transform motion-reduce:transition-none" style={{ transform: `scale(${p.zoom / 100})`, filter: `brightness(${p.brightness}%) contrast(${p.contrast}%)` }}><Image src={chestImage} width={600} height={720} alt="Synthetic educational chest radiograph" className="h-full w-full object-contain"/>{resultReady && p.overlay && p.study.finding && <div data-testid="ai-overlay" className="absolute rounded border-2 border-amber-300 bg-amber-300/15 shadow-[0_0_24px_rgba(252,211,77,.35)]" style={{ left: `${p.study.finding.box.left}%`, top: `${p.study.finding.box.top}%`, width: `${p.study.finding.box.width}%`, height: `${p.study.finding.box.height}%` }}/>} {p.annotations && <span className="absolute bottom-2 left-2 rounded bg-black/70 px-2 py-1 text-[9px] text-slate-300">SYNTHETIC · PA · W 1850 / L 900</span>}</div><div className="absolute bottom-2 right-2 rounded bg-black/70 px-2 py-1 text-[9px] text-amber-200">Synthetic educational image — not for diagnostic use</div></div>
        <div className="grid gap-2 border-t border-white/10 bg-[#0b1119] p-3 sm:grid-cols-3"><Meta label="Clinical indication" value={p.study.indication}/><Meta label="Comparison" value={p.study.comparison}/><Meta label="Series" value="1 / 1 · Frontal synthetic view"/></div></main>
      <RightPanel {...p}/></div></div>;
}

function ViewerToolbar(p: { overlay: boolean; annotations: boolean; zoom: number; brightness: number; contrast: number; onOverlay: () => void; onAnnotations: () => void; onZoom: (v: number) => void; onBrightness: (v: number) => void; onContrast: (v: number) => void; onResetView: () => void }) {
  return <div className="flex flex-wrap items-center gap-1 border-b border-white/10 bg-[#0f1620] p-2"><IconButton label="Zoom out" onClick={() => p.onZoom(Math.max(75, p.zoom - 25))}><Minus size={15}/></IconButton><span data-testid="zoom-value" className="w-12 text-center text-[10px] text-slate-400">{p.zoom}%</span><IconButton label="Zoom in" onClick={() => p.onZoom(Math.min(175, p.zoom + 25))}><Plus size={15}/></IconButton><IconButton label="Reset view" onClick={p.onResetView}><RotateCcw size={15}/></IconButton><IconButton label="Toggle AI overlay" pressed={p.overlay} onClick={p.onOverlay}>{p.overlay ? <Eye size={15}/> : <EyeOff size={15}/>}</IconButton><IconButton label="Toggle annotations" pressed={p.annotations} onClick={p.onAnnotations}><PanelRight size={15}/></IconButton><label className="ml-2 flex items-center gap-2 text-[10px] text-slate-400"><SlidersHorizontal size={13}/> Brightness<input aria-label="Brightness" type="range" min="70" max="140" value={p.brightness} onChange={(e) => p.onBrightness(Number(e.target.value))} className="w-20"/></label><label className="flex items-center gap-2 text-[10px] text-slate-400">Contrast<input aria-label="Contrast" type="range" min="70" max="150" value={p.contrast} onChange={(e) => p.onContrast(Number(e.target.value))} className="w-20"/></label></div>;
}

function RightPanel(p: { study: Study; analysis: string; stage: number; disposition: Disposition; report: string; audit: string[]; activeTab: "finding" | "report" | "history"; copied: boolean; onRetry: () => void; onDisposition: (v: Disposition) => void; onGenerate: () => void; onReport: (v: string) => void; onTab: (v: "finding" | "report" | "history") => void; onCopy: () => void }) {
  return <aside className="min-w-0 bg-[#0b1119]"><div className="grid grid-cols-3 border-b border-white/10">{([["finding", CircleHelp, "Findings"], ["report", FileText, "Report"], ["history", History, "Audit"]] as const).map(([id, Icon, label]) => <button type="button" key={id} onClick={() => p.onTab(id)} className={`flex items-center justify-center gap-1.5 border-b-2 px-2 py-3 text-[10px] font-bold ${p.activeTab === id ? "border-blue-500 text-blue-300" : "border-transparent text-slate-500"}`}><Icon size={13}/>{label}</button>)}</div>
    <div className="h-[550px] overflow-y-auto p-4">{p.activeTab === "finding" && <Findings {...p}/>} {p.activeTab === "report" && <Report {...p}/>} {p.activeTab === "history" && <Audit audit={p.audit}/>}</div></aside>;
}

function Findings(p: { study: Study; analysis: string; stage: number; disposition: Disposition; onRetry: () => void; onDisposition: (v: Disposition) => void; onGenerate: () => void }) {
  if (p.analysis === "idle") return <EmptyPanel title="Analysis not started" text="Run the scripted local pipeline to populate AI review results."/>;
  if (p.analysis === "processing") return <div><p className="text-xs font-bold">Processing synthetic images</p><div className="mt-4 space-y-3">{stages.map((s, i) => <div key={s} className={`flex items-center gap-3 rounded border p-3 text-xs ${i <= p.stage ? "border-blue-500/30 bg-blue-500/10 text-slate-200" : "border-white/10 text-slate-600"}`}><span className={`grid size-5 place-items-center rounded-full ${i < p.stage ? "bg-emerald-500 text-black" : "bg-white/10"}`}>{i < p.stage ? <Check size={12}/> : i + 1}</span>{s}</div>)}</div></div>;
  if (p.analysis === "error") return <div className="rounded border border-red-400/30 bg-red-400/5 p-4"><AlertTriangle className="text-red-300" size={20}/><h4 className="mt-3 text-sm font-bold">Simulated processing error</h4><p className="mt-2 text-xs leading-5 text-slate-400">The local pipeline stopped safely. No result was produced.</p><button type="button" onClick={p.onRetry} className="mt-4 rounded bg-blue-600 px-3 py-2 text-xs font-bold">Retry analysis</button></div>;
  if (!p.study.finding) return <div><EmptyPanel title="No suspected finding" text="The scripted pipeline did not flag an attention area. Review the full synthetic image independently."/><button type="button" onClick={p.onGenerate} className="mt-4 w-full rounded bg-blue-600 px-3 py-2 text-xs font-bold">Generate no-finding draft</button></div>;
  const f = p.study.finding;
  return <div><div className="rounded border border-amber-300/30 bg-amber-300/5 p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-[9px] font-bold uppercase tracking-wider text-amber-300">Suspected finding</p><h4 className="mt-1 text-sm font-bold">{f.name}</h4></div><Priority value={f.priority === "Urgent" ? "STAT" : "Routine"}/></div><dl className="mt-4 space-y-2 text-xs"><Row label="Location" value={`${f.laterality} ${f.location}`}/><Row label="Model output" value={f.confidence}/><Row label="Review" value="Requires radiologist review"/></dl><p className="mt-4 text-xs leading-5 text-slate-400">{f.evidence}</p></div><p className="mt-4 text-[10px] font-bold uppercase tracking-wider text-slate-500">Radiologist disposition</p><div className="mt-2 grid grid-cols-3 gap-1">{(["confirmed", "rejected", "uncertain"] as Disposition[]).map((d) => <button type="button" aria-pressed={p.disposition === d} key={d} onClick={() => p.onDisposition(d)} className={`rounded border px-1 py-2 text-[9px] font-bold capitalize ${p.disposition === d ? "border-blue-400 bg-blue-500/15 text-blue-200" : "border-white/10 text-slate-400 hover:bg-white/5"}`}>{d === "confirmed" ? "Confirm for draft" : d}</button>)}</div><div className="mt-4 rounded bg-white/[.03] p-3"><p className="text-[9px] font-bold uppercase tracking-wider text-slate-500">Suggested language</p><p className="mt-2 text-xs leading-5 text-slate-300">{p.disposition === "uncertain" ? f.cautiousSuggestion : p.disposition === "rejected" ? "Excluded from draft; preserved in audit." : f.suggestion}</p></div><button type="button" onClick={p.onGenerate} className="mt-4 w-full rounded bg-blue-600 px-3 py-2 text-xs font-bold">Generate structured draft</button><p className="mt-3 text-[9px] leading-4 text-amber-200">Not for diagnostic use — simulated demonstration</p></div>;
}

function Report(p: { report: string; copied: boolean; onReport: (v: string) => void; onCopy: () => void }) { return p.report ? <div><div className="flex items-center justify-between"><p className="text-xs font-bold">Structured draft</p><button type="button" onClick={p.onCopy} disabled={!navigator.clipboard} className="flex items-center gap-1 rounded px-2 py-1 text-[10px] text-blue-300 hover:bg-blue-500/10 disabled:opacity-40"><Clipboard size={12}/>{p.copied ? "Copied" : "Copy"}</button></div><textarea aria-label="Draft report editor" value={p.report} onChange={(e) => p.onReport(e.target.value)} className="mt-3 h-72 w-full resize-none rounded border border-white/10 bg-black/30 p-3 font-mono text-[10px] leading-5 text-slate-200 focus:border-blue-500 focus:outline-none"/><details className="mt-3 rounded border border-white/10 p-3"><summary className="cursor-pointer text-[10px] font-bold text-slate-300">Compare original findings context</summary><pre className="mt-3 whitespace-pre-wrap text-[9px] leading-4 text-slate-500">{reportContext}</pre></details><button type="button" disabled title="No clinical system connected" className="mt-3 w-full rounded border border-white/10 px-3 py-2 text-xs text-slate-600">Finalize · no clinical system connected</button></div> : <EmptyPanel title="No draft generated" text="Review the finding disposition, then generate a structured report draft."/>; }
function Audit({ audit }: { audit: string[] }) { return <ol className="space-y-4">{audit.map((item, i) => <li key={`${item}-${i}`} className="relative border-l border-white/10 pl-4 text-xs leading-5 text-slate-400"><span className="absolute -left-1 top-1 size-2 rounded-full bg-blue-400"/>{item}</li>)}</ol>; }
function Select({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (v: string) => void }) { return <label className="relative"><span className="sr-only">{label}</span><select aria-label={label} value={value} onChange={(e) => onChange(e.target.value)} className="appearance-none rounded-md border border-white/10 bg-[#0b1119] py-2 pl-3 pr-8 text-xs"><>{values.map((v) => <option key={v}>{v}</option>)}</></select><ChevronDown className="pointer-events-none absolute right-2 top-2.5 text-slate-500" size={12}/></label>; }
function IconButton({ label, onClick, pressed, children }: { label: string; onClick: () => void; pressed?: boolean; children: React.ReactNode }) { return <button type="button" aria-label={label} title={label} aria-pressed={pressed} onClick={onClick} className={`rounded p-2 hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-blue-400 ${pressed ? "bg-blue-500/15 text-blue-300" : "text-slate-400"}`}>{children}</button>; }
function Priority({ value }: { value: "STAT" | "Routine" }) { return <span className={`rounded px-2 py-1 text-[9px] font-bold ${value === "STAT" ? "bg-red-500/15 text-red-300" : "bg-slate-500/15 text-slate-300"}`}>{value}</span>; }
function AiBadge({ status }: { status: AiStatus }) { const styles = status === "attention" ? "bg-amber-400/10 text-amber-300" : status === "clear" ? "bg-emerald-400/10 text-emerald-300" : status === "error" ? "bg-red-400/10 text-red-300" : "bg-blue-400/10 text-blue-300"; return <span className={`rounded px-2 py-1 text-[9px] font-bold ${styles}`}>{statusLabel(status)}</span>; }
function statusLabel(status: AiStatus) { return ({ queued: "Pending", attention: "Attention", clear: "No finding", error: "Error" } as const)[status]; }
function priorityRank(status: AiStatus, priority: Study["priority"]) { return (status === "attention" ? 4 : status === "error" ? 3 : status === "queued" ? 2 : 1) + (priority === "STAT" ? 4 : 0); }
function Meta({ label, value }: { label: string; value: string }) { return <div><p className="text-[9px] font-bold uppercase tracking-wider text-slate-600">{label}</p><p className="mt-1 text-[10px] leading-4 text-slate-300">{value}</p></div>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-3"><dt className="text-slate-500">{label}</dt><dd className="text-right font-bold text-slate-300">{value}</dd></div>; }
function EmptyPanel({ title, text }: { title: string; text: string }) { return <div className="rounded border border-white/10 bg-white/[.025] p-5 text-center"><X className="mx-auto text-slate-600" size={22}/><h4 className="mt-3 text-sm font-bold">{title}</h4><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></div>; }
