import { cookies, headers } from "next/headers";
import { verifiedAccessEmail } from "./access";
export type RuntimeMode = "mock" | "node" | "cloud";
export function runtimeMode(): RuntimeMode { const value=process.env.ZGX_RUNTIME_MODE??"mock"; if(!["mock","node","cloud"].includes(value)) throw new Error("Invalid ZGX_RUNTIME_MODE"); return value as RuntimeMode; }
export async function isAdmin(): Promise<boolean> { const mode=runtimeMode(); if(mode==="mock") return process.env.ZGX_MOCK_ADMIN==="true"; if(mode==="node") return true; const incoming=await headers(); const assertedEmail=incoming.get("cf-access-authenticated-user-email")?.toLowerCase(); const accessJwt=incoming.get("cf-access-jwt-assertion")??(await cookies()).get("CF_Authorization")?.value; const email=assertedEmail??(accessJwt?await verifiedAccessEmail(accessJwt):null); const allowed=(process.env.ZGX_ADMIN_EMAILS??"").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean); if(email&&allowed.includes(email)) return true; const host=(incoming.get("host")??"").split(":")[0].toLowerCase(); return process.env.ZGX_LOCAL_ADMIN==="true" && (host==="127.0.0.1"||host==="localhost"||host==="::1"); }
function origin(){return process.env.ZGX_NODE_BRIDGE_ORIGIN??process.env.ZGX_NODE_ORIGIN??"http://127.0.0.1:60372"}
function bridgeHeaders(admin=false){const token=process.env.ZGX_BRIDGE_TOKEN??"";const result:Record<string,string>={};if(token)result.authorization=`Bearer ${token}`;if(admin&&process.env.ZGX_ADMIN_BRIDGE_SECRET)result["x-zgx-admin-secret"]=process.env.ZGX_ADMIN_BRIDGE_SECRET;return result}
export async function bridgeLive(){if(runtimeMode()==="mock")return true;try{const response=await fetch(new URL("/health",origin()),{cache:"no-store",signal:AbortSignal.timeout(2000)});return response.ok}catch{return false}}
const READ_PATHS=new Set(["/api/resources","/api/workloads","/api/policy"]);
export async function proxyRead(path:string,admin=false){if(!READ_PATHS.has(path) && !/^\/api\/workloads\/[a-z0-9-]+\/logs$/.test(path))return Response.json({error:"Route not allowed"},{status:404});return proxy(path,{method:"GET",headers:bridgeHeaders(admin)})}
export async function proxyMutation(path:string,body:unknown){if(!await isAdmin())return Response.json({error:"Admin access required"},{status:403});const allowed=path==="/api/transitions"||/^\/api\/workloads\/[a-z0-9-]+\/(?:stop|restart|emergency-stop)$/.test(path);if(!allowed)return Response.json({error:"Route not allowed"},{status:404});return proxy(path,{method:"POST",headers:{"content-type":"application/json",...bridgeHeaders(true)},body:JSON.stringify(body)})}
async function proxy(path:string,init:RequestInit){try{const upstream=await fetch(new URL(path,origin()),{...init,cache:"no-store",signal:AbortSignal.timeout(8000)});const body=await upstream.text();return new Response(body,{status:upstream.status,headers:{"content-type":upstream.headers.get("content-type")??"application/json","cache-control":"no-store"}})}catch{return Response.json({error:"ZGX Node is unavailable"},{status:503,headers:{"cache-control":"no-store"}})}}
