"use client";

import { useState } from "react";
import { Activity, Check, Database, Gauge, Layers3, Play, RotateCcw, ShieldCheck, Users } from "lucide-react";
import type { SimulationProps, SimulationState } from "../contracts";
import { getFuryExperienceConfig } from "./config";

export function FuryOperationsSimulation({ demo }: SimulationProps) {
  const config = getFuryExperienceConfig(demo);
  const [state, setState] = useState<SimulationState>("initial");
  const [selected, setSelected] = useState(0);
  if (!config) return null;
  const run = () => { setState("processing"); window.setTimeout(() => setState("success"), 850); };
  const active = config.queue[selected];

  return <section className="overflow-hidden rounded-[2rem] border border-[var(--line)] bg-[#07101f] text-slate-100 shadow-2xl shadow-blue-950/30" aria-label={`${demo.name} departmental simulation`}>
    <header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 px-5 py-4 md:px-7"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan-300">ZGX Fury · Departmental workspace</p><h2 className="mt-1 text-lg font-black">{config.workspace}</h2></div><div className="flex items-center gap-3"><span className="inline-flex items-center gap-2 rounded-full bg-emerald-400/10 px-3 py-1.5 text-xs font-bold text-emerald-300"><Activity size={13}/> Illustrative operations</span><button onClick={() => { setState("initial"); setSelected(0); }} className="grid size-9 place-items-center rounded-full border border-white/15" aria-label="Reset simulation"><RotateCcw size={15}/></button></div></header>
    <div className="grid min-h-[560px] lg:grid-cols-[280px_1fr]">
      <aside className="border-b border-white/10 bg-white/[.025] p-4 lg:border-b-0 lg:border-r"><div className="mb-3 flex items-center justify-between"><p className="text-xs font-black uppercase tracking-wider text-slate-400">Department queue</p><span className="rounded-full bg-blue-400/10 px-2 py-1 text-[10px] font-bold text-blue-300">{config.queue.length} ACTIVE</span></div><div className="space-y-2">{config.queue.map((item, index) => <button key={item.id} onClick={() => { setSelected(index); setState("initial"); }} className={`w-full rounded-xl border p-3 text-left transition ${selected === index ? "border-cyan-400/50 bg-cyan-400/10" : "border-white/10 bg-white/[.025] hover:bg-white/[.05]"}`}><div className="flex items-center justify-between gap-2"><span className="text-[10px] font-bold text-slate-500">{item.id}</span><span className={`text-[10px] font-black ${item.priority === "Priority" ? "text-amber-300" : "text-slate-400"}`}>{item.priority}</span></div><p className="mt-2 text-sm font-bold">{item.title}</p><p className="mt-1 text-xs text-slate-400">{item.detail}</p></button>)}</div></aside>
      <div className="p-5 md:p-7"><div className="grid gap-3 sm:grid-cols-3"><Metric icon={Users} label="Workspace" value="Multi-user"/><Metric icon={Layers3} label="AI services" value={`${config.services.length} coordinated`}/><Metric icon={ShieldCheck} label="Control mode" value="Human approval"/></div>
        <div className="mt-6 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><div className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold text-cyan-300">{active.id}</p><h3 className="mt-1 text-xl font-black">{active.title}</h3><p className="mt-2 text-sm text-slate-400">{config.liveLabel} coordinates several resident AI services and routes every consequential output to review.</p></div><button onClick={run} disabled={state === "processing"} className="inline-flex items-center gap-2 rounded-xl bg-cyan-400 px-4 py-2.5 text-sm font-black text-slate-950 disabled:opacity-60"><Play size={15}/>{state === "processing" ? "Orchestrating…" : "Run scenario"}</button></div>
          <div className="mt-6 space-y-3">{config.services.map((service, index) => <div key={service} className="flex items-center gap-3 rounded-xl border border-white/10 p-3"><span className={`grid size-8 place-items-center rounded-lg ${state === "success" || (state === "processing" && index < 2) ? "bg-emerald-400/10 text-emerald-300" : "bg-white/5 text-slate-500"}`}>{state === "success" ? <Check size={15}/> : <Database size={14}/>}</span><div className="flex-1"><p className="text-sm font-bold">{service}</p><p className="text-xs text-slate-500">{state === "success" ? "Output ready for governed handoff" : state === "processing" ? "Processing illustrative workload" : "Ready"}</p></div><span className="text-[10px] font-bold text-slate-500">SERVICE {index + 1}</span></div>)}</div></div>
          <aside className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><p className="text-xs font-black uppercase tracking-wider text-slate-400">Governed outputs</p><div className="mt-4 space-y-3">{config.outputs.map((output) => <div key={output} className="rounded-xl bg-black/20 p-3"><div className="flex items-center gap-2"><span className={`size-2 rounded-full ${state === "success" ? "bg-emerald-400" : "bg-slate-600"}`}/><p className="text-sm font-bold">{output}</p></div><p className="mt-2 text-xs leading-5 text-slate-500">{state === "success" ? "Prepared with provenance and queued for human approval." : "Generated after the scenario is run."}</p></div>)}</div><div className="mt-5 rounded-xl border border-amber-300/20 bg-amber-300/5 p-3 text-xs leading-5 text-amber-100">This deterministic simulation demonstrates workflow scope, not measured throughput, latency, or user capacity.</div></aside></div>
      </div>
    </div>
  </section>;
}

function Metric({ icon: Icon, label, value }: { icon: typeof Gauge; label: string; value: string }) { return <div className="rounded-xl border border-white/10 bg-white/[.025] p-4"><Icon size={16} className="text-cyan-300"/><p className="mt-3 text-[10px] font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-sm font-black">{value}</p></div>; }
