"use client";

import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, CircleHelp, MessageSquareQuote, Target } from "lucide-react";
import { useMemo, useState } from "react";
import { industries } from "@/data/catalog";

export default function DiscussionPage() {
  const [industrySlug, setIndustrySlug] = useState(industries[0].slug);
  const industry = industries.find((item) => item.slug === industrySlug) ?? industries[0];
  const [demoSlug, setDemoSlug] = useState(industry.demos[0].slug);
  const demo = useMemo(() => industry.demos.find((item) => item.slug === demoSlug) ?? industry.demos[0], [industry, demoSlug]);
  const changeIndustry = (slug: string) => { const next = industries.find((item) => item.slug === slug) ?? industries[0]; setIndustrySlug(slug); setDemoSlug(next.demos[0].slug); };
  return <div className="shell pt-14"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="eyebrow">Seller preparation</p><h1 className="gradient-text mt-4 text-5xl font-black tracking-[-.05em] md:text-6xl">Discussion guide</h1><p className="muted mt-5 max-w-2xl text-lg leading-8">Prepare discovery questions and talking points away from the customer-facing simulation.</p></div><Link href={`/demos/${demo.slug}`} className="inline-flex items-center gap-2 font-bold text-blue-500">Open customer demo <ArrowRight size={17}/></Link></div>
    <section className="panel mt-10 grid gap-4 rounded-3xl p-5 sm:grid-cols-2"><label className="text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Industry<select value={industrySlug} onChange={(event)=>changeIndustry(event.target.value)} className="mt-2 block w-full rounded-xl border border-[var(--line)] bg-[var(--bg)] p-3 text-sm normal-case text-[var(--text)]">{industries.map((item)=><option value={item.slug} key={item.slug}>{item.name}</option>)}</select></label><label className="text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Demo<select value={demo.slug} onChange={(event)=>setDemoSlug(event.target.value)} className="mt-2 block w-full rounded-xl border border-[var(--line)] bg-[var(--bg)] p-3 text-sm normal-case text-[var(--text)]">{industry.demos.map((item)=><option value={item.slug} key={item.slug}>{item.name}</option>)}</select></label></section>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><GuideSection icon={BriefcaseBusiness} title="Typical buyers"><div className="flex flex-wrap gap-2">{demo.personas.map((persona)=><span key={persona} className="rounded-full border border-[var(--line)] px-3 py-2 text-xs font-bold">{persona}</span>)}</div></GuideSection><GuideSection icon={Target} title="Customer pain points"><ul className="space-y-3">{demo.painPoints.map((point)=><li key={point} className="muted flex gap-3 text-sm"><span className="text-blue-500">◆</span>{point}</li>)}</ul></GuideSection><GuideSection icon={CircleHelp} title="Discovery questions"><ol className="space-y-3">{demo.questions.map((question,index)=><li key={question} className="flex gap-4 rounded-xl border border-[var(--line)] p-4"><span className="text-xs font-black text-blue-500">{String(index+1).padStart(2,"0")}</span><span className="text-sm leading-6">{question}</span></li>)}</ol></GuideSection><GuideSection icon={MessageSquareQuote} title="Objection handling"><div className="space-y-3">{demo.objections.map((item)=><div key={item.objection} className="rounded-xl border border-[var(--line)] p-4"><p className="text-sm font-bold">“{item.objection}”</p><p className="muted mt-2 text-sm leading-6">{item.response}</p></div>)}</div></GuideSection><GuideSection icon={Target} title="Business outcomes"><div className="grid gap-3 sm:grid-cols-2">{demo.outcomes.map((outcome)=><div key={outcome} className="rounded-xl border border-[var(--line)] p-4 text-sm font-bold">{outcome}</div>)}</div></GuideSection><GuideSection icon={ArrowRight} title="Suggested next step"><p className="muted leading-7">Confirm the highest-value workflow, identify representative data and stakeholders, and define a bounded proof of concept with measurable success criteria.</p></GuideSection></div>
  </div>;
}

function GuideSection({ icon: Icon, title, children }: { icon: typeof Target; title: string; children: React.ReactNode }) { return <section className="panel rounded-3xl p-7"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-blue-500/10 text-blue-500"><Icon size={19}/></span><h2 className="text-xl font-black">{title}</h2></div><div className="mt-6">{children}</div></section>; }
