"use client";
import { useCallback,useEffect,useState } from "react";
import { Calculator,Cpu,GraduationCap,LayoutDashboard,Moon,Sun } from "lucide-react";
import type { AdminBookingData } from "@/lib/bookings-types";
import { consoleHash,normalizeSimulationPath,parseConsoleHash,type ConsoleTab } from "@/lib/navigation";
import { trackZgxInteraction,useZgxTelemetry } from "@/lib/telemetry";
import { SimulationFrame } from "./SimulationFrame"; import { NodeDashboard } from "./NodeDashboard"; import { SivaAdminFrame } from "./SivaAdminFrame"; import { DemoBookingAdmin } from "./DemoBookingAdmin"; import { EnterpriseInsights } from "./EnterpriseInsights"; import { TcoCalculator } from "./TcoCalculator";
const tabs=[{id:"simulation",number:"01",label:"Experiences",icon:LayoutDashboard},{id:"node",number:"02",label:"Device",icon:Cpu},{id:"insights",number:"03",label:"Enterprise Guide",icon:GraduationCap},{id:"tco",number:"04",label:"Cost Analysis",icon:Calculator}] as const;
type Theme="light"|"dark";
export function ConsoleShell({initialTab="simulation",adminView=false,adminBookingData}:{initialTab?:ConsoleTab;adminView?:boolean;adminBookingData?:AdminBookingData}){
 const[tab,setTab]=useState<ConsoleTab>(initialTab),[simulationPath,setSimulationPath]=useState("/"),[theme,setTheme]=useState<Theme>("light");
 useZgxTelemetry(tabs.find(item=>item.id===tab)?.label||"Experiences",!adminView);
 useEffect(()=>{const timer=window.setTimeout(()=>{try{const saved=localStorage.getItem("zgx-theme");if(saved==="light"||saved==="dark")setTheme(saved)}catch{}},0);return()=>window.clearTimeout(timer)},[]);
 useEffect(()=>{if(adminView)return;const tabName=tabs.find(entry=>entry.id===tab)?.label||tab,capture=(event:MouseEvent)=>{const target=event.target instanceof Element?event.target.closest<HTMLElement>(".page button,.page a,[data-analytics-item]"):null;if(!target||target.closest(".chapter-nav"))return;const item=target.dataset.analyticsItem||target.getAttribute("aria-label")||target.textContent?.trim().replace(/\s+/g," ").slice(0,100);if(item)trackZgxInteraction(tabName,"feature_click",item,tab)},captureChange=(event:Event)=>{const target=event.target instanceof Element?event.target.closest<HTMLInputElement|HTMLSelectElement>(".page input,.page select"):null;if(!target)return;const label=target.getAttribute("aria-label")||target.name||target.id||target.closest("label")?.childNodes[0]?.textContent?.trim().slice(0,80);if(label)trackZgxInteraction(tabName,"feature_change",label,tab)};document.addEventListener("click",capture);document.addEventListener("change",captureChange);return()=>{document.removeEventListener("click",capture);document.removeEventListener("change",captureChange)}},[adminView,tab]);
 useEffect(()=>{document.documentElement.dataset.theme=theme},[theme]);
 useEffect(()=>{const apply=()=>{if(!window.location.hash){setTab(initialTab);return}const next=parseConsoleHash(window.location.hash);setTab(next.tab);if(next.tab==="simulation")setSimulationPath(next.simulationPath)};apply();window.addEventListener("hashchange",apply);window.addEventListener("popstate",apply);return()=>{window.removeEventListener("hashchange",apply);window.removeEventListener("popstate",apply)}},[initialTab]);
 const writeUrl=useCallback((nextTab:ConsoleTab,path="/",replace=false)=>{const hash=consoleHash(nextTab,path);if(window.location.hash===hash)return;window.history[replace?"replaceState":"pushState"](null,"",hash)},[]);
 function select(id:ConsoleTab){setTab(id);writeUrl(id,id==="simulation"?simulationPath:"/")}
 function resetDemo(){setTab("simulation");setSimulationPath("/");writeUrl("simulation","/")}
 const simulationRouteChanged=useCallback((path:string)=>{const next=normalizeSimulationPath(path),parts=next.split("/").filter(Boolean),platform=parts[0];setSimulationPath(next);writeUrl("simulation",next);if(platform==="nano"||platform==="fury"){trackZgxInteraction("Experiences","demo_platform",platform);if(parts.length>=3)trackZgxInteraction("Experiences","demo_experience",parts.slice(2).join("/"),`${platform}:${parts[1]}`) }},[writeUrl]);
 function toggleTheme(){setTheme(value=>{const next=value==="dark"?"light":"dark";try{localStorage.setItem("zgx-theme",next)}catch{}return next})}
 return <><main className="shell"><header className="topbar"><a className="brand" href="#experiences" onClick={event=>{event.preventDefault();resetDemo()}}><span className="brand-mark">Z</span><span><strong>ZGX Console</strong><small>Personal AI infrastructure</small></span></a><div className="topbar-actions"><span className="nano-pill"><i/> {adminView?"Authorized admin":"ZGX Console"}</span><button className="theme-toggle" type="button" aria-label={`Switch to ${theme==="dark"?"light":"dark"} theme`} onClick={toggleTheme}>{theme==="dark"?<Sun size={17}/>:<Moon size={17}/>}</button></div></header><nav className="tabs" aria-label="ZGX Console sections">{tabs.map(item=><button key={item.id} className={tab===item.id?"active":""} onClick={()=>select(item.id)} aria-current={tab===item.id?"page":undefined}><b>{item.number}</b><item.icon size={17}/><span>{item.label}</span></button>)}</nav><section className="page" key={tab}>{tab==="simulation"&&<SimulationFrame theme={theme} path={simulationPath} onPathChange={simulationRouteChanged}/>} {tab==="node"&&(adminView?<><SivaAdminFrame/><DemoBookingAdmin initialData={adminBookingData}/></>:<NodeDashboard/>)} {tab==="insights"&&<EnterpriseInsights/>}{tab==="tco"&&<TcoCalculator/>}</section></main></>
}
